/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        int[] n = new int[] { 1, 2, 3, 4, 5, 6, 7, 8};
        int k = 3;

        System.out.println(doAlgorithm(n, k, 0, ""));
    }

    public static String doAlgorithm(int[] n, int k, int index, String begin)
    {
        if(k == 0)
            return begin + "\n";
        
        String retval = "";
        for(int i = index; i < n.length; i++)
        {
            retval += doAlgorithm(n, k-1, 1+i, begin + n[i] + " ");
        }
        return retval;
    }

    
}
